name: Build APK on Push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "16.x"
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install dependencies
        run: |
          flutter upgrade
          flutter pub upgrade
          flutter pub get
      - name: Build APK
        run: |
          flutter build apk --split-per-abi -v
      - name: Upload APK to Telegram
        run: |
          curl --form-string chat_id=${{ vars.CHAT_ID }} -F document=@build/app/outputs/apk/release/app-arm64-v8a-release.apk https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument
